package com.franzandel.dicodingexpertsubmission.domain.model.remote.response

data class GamesResult(
    val added: Int,
    val addedByStatus: AddedByStatus,
    val backgroundImage: String,
    val clip: Any?,
    val dominantColor: String,
    val esrbRating: EsrbRating?,
    val genres: List<Genre>,
    val id: Int,
    val metacritic: Int,
    val name: String,
    val parentPlatforms: List<ParentPlatform>,
    val platforms: List<ResultPlatform>,
    val playtime: Int,
    val rating: Double,
    val ratingTop: Int,
    val ratings: List<Rating>,
    val ratingsCount: Int,
    val released: String,
    val reviewsCount: Int,
    val reviewsTextCount: Int,
    val saturatedColor: String,
    val shortScreenshots: List<ShortScreenshot>,
    val slug: String,
    val stores: List<ResultStore>,
    val suggestionsCount: Int,
    val tags: List<Tag>,
    val tba: Boolean,
    val updated: String,
    val userGame: Any?
)